// File generated by https://app.quicktype.io/

import 'dart:convert';

Assignment assignmentFromJson(String str) => Assignment.fromJson(json.decode(str));

String assignmentToJson(Assignment data) => json.encode(data.toJson());

class Assignment {
  String id = DateTime.now().millisecondsSinceEpoch.toString();
  String title;
  String notes;
  DateTime startDate;
  DateTime endDate;
  int spentMinutes;
  bool finished;

  int get durationMinutes {
    return endDate.difference(startDate).inMinutes;
  }

  String get statusStr {

    if(spentMinutes == null || spentMinutes == 0){
      return "Not started yet";
    }

    if(durationMinutes != null && durationMinutes > 0){
      return "Completed ${((spentMinutes / durationMinutes)*100).floor()}%";
    }

    return "No status";

  }

  Assignment();

  Assignment._new({
    this.id,
    this.title,
    this.notes,
    this.startDate,
    this.endDate,
    this.spentMinutes,
    this.finished,
  });

  factory Assignment.fromJson(Map<String, dynamic> json) => Assignment._new(
    id: json["id"],
    title: json["title"],
    notes: json["notes"],
    startDate: DateTime.parse(json["startDate"]),
    endDate: DateTime.parse(json["endDate"]),
    spentMinutes: json["spent_minutes"],
    finished: json["finished"],
  );

  Map<String, dynamic> toJson() => {
    "id": id,
    "title": title,
    "notes": notes,
    "startDate": startDate.toIso8601String(),
    "endDate": endDate.toIso8601String(),
    "spent_minutes": spentMinutes,
    "finished": finished,
  };
}