// File generated by https://app.quicktype.io/

import 'dart:convert';

Assignment assignmentFromJson(String str) => Assignment.fromJson(json.decode(str));

String assignmentToJson(Assignment data) => json.encode(data.toJson());

class Assignment {
  String title;
  String notes;
  DateTime startDate;
  DateTime endDate;

  Assignment({
    this.title,
    this.notes,
    this.startDate,
    this.endDate,
  });

  factory Assignment.fromJson(Map<String, dynamic> json) => Assignment(
    title: json["title"],
    notes: json["notes"],
    startDate: DateTime.parse(json["startDate"]),
    endDate: DateTime.parse(json["endDate"]),
  );

  Map<String, dynamic> toJson() => {
    "title": title,
    "notes": notes,
    "startDate": startDate.toIso8601String(),
    "endDate": endDate.toIso8601String(),
  };
}